category_patterns_dict = {'breast': [r'(breast(?:s)?|boob(?:s)?) (hurt|(is|are) (sore|sensitive|tender))',
                                     r'soreness of (breast(?:s)?|boob(?:s)?)',
                                     r'(tender|sore|sensitive) (breast(?:s)?|boob(?:s)?)',
                                     r'(breast(?:s)?|boob(?:s)?) pain',
                                     r'(chest|breast(?:s)?|boob(?:s)?) grew',
                                     r'(chest|breast(?:s)?|boob(?:s)?) got bigger'],
                        'dizziness': ['dizzy',
                                      'dizziness',
                                      'light-headed',
                                      'light headed',
                                      'lightheaded',
                                      'faint', 
                                      'pass out',
                                      'passed out'],
                        'blood pressure': ['blood pressure'],
                        'nausea': ['nausea', 
                                   'naseuous', 
                                   'sick to my stomach', 
                                   'queasy', 
                                   'vomit', 
                                   'throw up', 
                                   'puke',
                                   'puking'],
                        'skin': ['skin is clearing up', 
                                 'breaking out',
                                 'broke out',
                                 'break out',
                                 'acne', 
                                 'pimples', 
                                 'melasma'], 
                        'bleeding': ['spotting',
                                     'breakthrough bleed',
                                     'bleed nonstop',
                                     'period nonstop',
                                     'nonstop period',
                                     'heavy period',
                                     r'period(?:s)? (became|is|are) (heavy|light|irregular)',
                                     'bleed',
                                     'heavy period',
                                     'light period'], 
                        'no period': ['missed period',
                                      'missed my period'
                                      'skipped period',
                                      'skipped my period',
                                      'no period'],
                        'appetite': ['appetite',
                                     'craving',
                                     'hungry'],
                        'weight gain': [r'(gain(?:ed)?) a (couple|few) pounds', 
                                        r'(gain(?:ed)?) weight',
                                        r'(gain(?:ed)?) [a-z0-9]+ (pounds|kilograms|lb|lbs|kg|stone)'],
                        'mood': ['anxiety', 
                                 'mood', 
                                 'depression', 
                                 'depressed', 
                                 'anxious', 
                                 'anxiety',
                                 'mental health', 
                                 'panic attack', 
                                 'irritable', 
                                 'irritability',
                                 'emotional'], 
                        'libido': ['sex drive', 
                                   'sexual drive',
                                   'libido'],
                        'bloating': ['bloat',
                                     'water retention'],
                        'fatigue': ['sleepy', 
                                    'can\'t sleep', 
                                    'tired all the time', 
                                    'always feel tired', 
                                    'exhausted',
                                    'fatigue', 
                                    'always tired'], 
                        'pms': ['pms'],
                        'hair loss': ['hair loss',
                                      'hair fell',
                                      'hair thinning',
                                      'bald',
                                      'hair fall',
                                      'hair shed'],
                        'headache': ['headache', 
                                     'head hurt',
                                     'head ache',
                                     'migraine'],
                        'infection': ['infection', 
                                      'uti'], 
                        'heart attack': ['heart attack'],
                        'stroke': ['blood clot', 
                                   'pulmonary embolism', 
                                   'stroke'],
                        'discharge': ['discharge'],
                        'dryness': ['lubricat', 
                                    'dryness', 
                                    'wet'],
                        'cramps': ['cramp', 
                                   'period pain', 
                                   'painful period', 
                                   'pain from my period'],
                        'pain': ['painful', 
                                 'pain', 
                                 'hurt',
                                 'agony',
                                 'cramp',
                                 'throb',
                                 'stabbing',
                                 'stabbed',
                                 'ache'], 
                        'felt strings': ['pok(ed|ing) (him|them|my boyfriend|my husband|my partner)', 
                                         r'(partner|husband|boyfriend|bf|he|they) (could feel|felt) (my|the) (strings|iud)'],
                        'general': ['side effect']}